name: Test & Deploy
on:
  workflow_dispatch:
    branches:
      - main
      - "*.*.*"
  push:
    branches:
      - main
    paths:
      - packages/**
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: cache installed dependencies
        uses: actions/cache@v4
        id: get-node-modules
        with:
          path: node_modules
          key: deps-node-modules-${{ hashFiles('**/package-lock.json')}}
      - name: install dependencies
        if: steps.get-node-modules.outputs.cache-hit != 'true'
        run: npm install
      - name: upload test report
        if: failure() && steps.cl.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: test.json
  report:
    runs-on: ubuntu-latest
    needs: test
    if: failure()
    steps:
      - name: outputs
        run: |
          echo "Something went wrong"
          echo "${{github}}"
  deploy:
    runs-on: ubuntu-latest
    needs: test
    environment: main
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: cache installed dependencies
        uses: actions/cache@v4
        id: get-node-modules
        with:
          path: node_modules
          key: deps-node-modules-${{ hashFiles('**/package-lock.json')}}
      - name: install dependencies
        if: steps.get-node-modules.outputs.cache-hit != 'true'
        run: npm install
      - name: semantic-release
        run: npm run deploy --workspaces --if-present
        env:
          GITHUB_TOKEN: ${{ github.token }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GIT_AUTHOR_NAME: "Alexandros Karagiannis"
          GIT_AUTHOR_EMAIL: "pp.alexkara@gmail.com"
          GIT_COMMITTER_NAME: "Alexandros Karagiannis"